--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XanderID-MC/EconomyEnchant
build-by-default: true
branches:
- main
projects:
  EconomyEnchant:
    path: ""
    icon: "icon.png"
    libs:
      - src: XanderID/PocketForm/PocketForm
        version: ^1.0.1
      - src: LatamPMDevs/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
      - src: LatamPMDevs/ConfigUpdater/ConfigUpdater
        version: ^2.0.1
      - src: muqsit/InvMenu/InvMenu
        branch: "pm5"
        version: ^4.6.5
    lint: false
...
