---
# Please don't edit this, only for internal use
config-version: 4

# Your Economy plugin name
# Available: BedrockEconomy, XP, Auto
# If you select auto but there is no Economy Plugin it will automatically use XP
economy: "Auto"

# Can EnchantTable Redirect to EconomyEnchant
enchant-table: true

# Add Anvil Sound to Player if Enchant is Successful
sound: true

# Form Type
# Can use UI or GUI
form-type: "UI"

# Form
form:
 # Buy Menu
 buy-shop:
  # Title for BuyShop
  title: "EnchantShop"
  # Content for BuyShop
  content: "Select Enchantment:"
  # Tag: {price} Price Enchantment, {enchant} Name Of Enchantment
  button:
   # Only can 0-1
   0: "{enchant}"
   1: "{price}"
 # Submit Menu
 submit:
  # Title for SubmitMenu
  title: "EnchantShop"
  # Content
  # Tag: {price} Price of Enchantment
  content: "§aYou will pay {price} Per Level"
  # Max Content
  max-content: "§aYour item has reached the level limit!"
  # Slider Content
  slider: "Level"
  # Button
  button: "Enchant Item"

# GUI
gui:
 # Buy Menu
 buy-shop:
  # Title for BuyShop
  title: "EnchantShop"
  # Tag: {level} Level Enchantment, {enchant} Name Of Enchantment
  name: "§f{enchant} §b{level}"
  # Tag: {price} Price Enchantment
  # if you want to empty lore just put value []
  lore:
   - "Price for This Enchant {price}"
 # Submit Menu
 submit:
  # Title for SubmitMenu
  title: "EnchantShop"
  # Buy Item
  buy:
   # Buy Item Name
   # Tag: {level} Level Enchantment, {enchant} Name Of Enchantment
   name: "Buy §f{enchant} §b{level}"
   # Buy Item Lore
   # Tag: {price} Price Enchantment
   # if you want to empty lore just put value []
   lore:
    - "Are you sure to buy"
    - "This Enchant With price {price}"
   # Cancel Item
  cancel:
   # Cancel Item Name
   name: "§cCancel"
   # Cancel Item Lore
   # if you want to empty lore just put value []
   lore:
    - "Cancel buying Enchantment"

# Message
message:
 # Cannot Enchant On This Item
 err-item: "§cYou cannot add Enchantment to This Item!"
 # Enchantment doesn't Exists
 err-enchant: "§cThis enchantment is not available!"
 # Exit Message
 exit: "§aThank you for visiting!"
 # Successfully Buy Enchant
 # Tag: {enchant} Name Enchantment, {item} Name Item, {price} Price Enchantment
 success: "§aSuccessfully Enchant {enchant} to {item}, with Price {price}"
 # Error Money not Enough
 # Tag: {need} Needed Money
 enough: "§cYour money is not enough need {need}"

# Mode
# If false Enchantment those that are not set will not be in the shop
# If true Enchantment Auto added and price will be to Default ( Not Setted )
mode: true

# Enchantment
enchantment:
 # Name Enchantment
 sharpness:
  # Price
  price: 1000
 # Default, If the enchantment is not set above
 # it will be redirected here
 default:
  # Price
  price: 10000
  
# Blacklist Enchantment from Shop
# if you want blacklist just add
# example: ["sharpness", "silk_touch"] or ["sharpness"]
blacklist: []

# Blacklist Enchantment from Item
# if you want blacklist just add
# example: 
# blacklist:
#  sharpness: ["diamond_sword"]
blacklist-item: []
...
